version: "3.7"
services:
  clients:
    container_name: clients
    restart: always
    build: 
      network: host
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo-server   
  products:
    container_name: products
    restart: always
    build: 
      network: host
      context: ../Microservicio-productos/.
    ports:
      - "4000:4000"
    depends_on:
      - mongo-server     
  mongo-server:
    container_name: mongo-server
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
